// Code generated by MockGen. DO NOT EDIT.
// Source: server.go

// Package tcp is a generated GoMock package.
package tcp

import (
	context "context"
	net "net"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTCPHandler is a mock of TCPHandler interface.
type MockTCPHandler struct {
	ctrl     *gomock.Controller
	recorder *MockTCPHandlerMockRecorder
}

// MockTCPHandlerMockRecorder is the mock recorder for MockTCPHandler.
type MockTCPHandlerMockRecorder struct {
	mock *MockTCPHandler
}

// NewMockTCPHandler creates a new mock instance.
func NewMockTCPHandler(ctrl *gomock.Controller) *MockTCPHandler {
	mock := &MockTCPHandler{ctrl: ctrl}
	mock.recorder = &MockTCPHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTCPHandler) EXPECT() *MockTCPHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockTCPHandler) Handle(ctx context.Context, conn net.Conn) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Handle", ctx, conn)
}

// Handle indicates an expected call of Handle.
func (mr *MockTCPHandlerMockRecorder) Handle(ctx, conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockTCPHandler)(nil).Handle), ctx, conn)
}
